# Render.com Deployment Configuration for Laravel

# Build Command
composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force

# Start Command  
php artisan serve --host=0.0.0.0 --port=$PORT

# Environment Variables Required:
# APP_NAME=PetCare API
# APP_ENV=production
# APP_KEY=[Generate with: php artisan key:generate --show]
# APP_DEBUG=false
# APP_URL=https://your-app-name.onrender.com
# DB_CONNECTION=pgsql
# DB_HOST=[From Render PostgreSQL service]
# DB_PORT=5432
# DB_DATABASE=[From Render PostgreSQL service]
# DB_USERNAME=[From Render PostgreSQL service]
# DB_PASSWORD=[From Render PostgreSQL service]
# CORS_ALLOWED_ORIGINS=https://your-frontend-url.vercel.app